Handle error during connection in sleep mode.
aparraga/braviarc pull request #10
Opened 2016-11-12 15:27 UTC by ngraziano

If TV is in sleep mode (not totally off) when I try to connect, its response  is :
```json
{"error":[7,"not power-on"],"id":1}
```
and there is not the necessary cookie for authentication but `is_connected()` return `True` 

I get sleep mode for few minutes when I turn the TV off.

2016-11-12 18:12 UTC, aparraga commented on braviarc/braviarc.py
> +            resp = json.loads(response.content.decode('utf-8'))
does response always have a content attribute snd content is alwais not null at this point?

2016-11-12 18:13 UTC, antonioparraga reviewed
good fix, however please see my question

2016-11-13 11:42 UTC, ngraziano commented
I change to use response.json(), it was use before for log so this should be good.
I also change the test to be allow null response.

2016-11-13 11:44 UTC, antonioparraga requested changes

2016-11-13 11:44 UTC, aparraga commented on braviarc/braviarc.py
> +            _LOGGER.info(json.dumps(resp, indent=4))
Should be debug instead of info at this point?

2016-11-13 21:19 UTC, merged

2016-11-13 21:19 UTC, aparraga commented
perfect!