Fixing the limit of 50 sources getting the source list
aparraga/braviarc pull request #9
Opened 2016-11-08 17:23 UTC by trunet

2016-11-08 18:11 UTC, antonioparraga requested changes

2016-11-08 18:11 UTC, aparraga commented on braviarc/braviarc.py
> +        stIdx = 0
var name does not fit python coding standards (https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles)

2016-11-08 18:11 UTC, aparraga commented on braviarc/braviarc.py
> +                    stIdx = resp.get('result')[0][-1]['index']+1
why? a -1 index? could you please paste an example of data returned by your TV showing the -1 key just for clarification?

2016-11-08 18:11 UTC, aparraga commented on braviarc/braviarc.py
> +        while True:
we have to avoid infinite loops + breaks. are u able to refactor this loop with a termination condition instead of breaks here and there?

2016-11-08 18:11 UTC, aparraga commented on braviarc/braviarc.py
> +                if result['source'] in ['tv:dvbc', 'tv:dvbt']:  # tv:dvbc = via cable, tv:dvbt = via DTT
good point!

2016-11-08 18:13 UTC, trunet commented on braviarc/braviarc.py
> +                    stIdx = resp.get('result')[0][-1]['index']+1
-1 is just to get the last item from the list, so it get the last index and sum one.

2016-11-08 18:14 UTC, trunet commented on braviarc/braviarc.py
> +        stIdx = 0
I will change the var names

2016-11-08 18:14 UTC, trunet commented on braviarc/braviarc.py
> +        while True:
I don't know, let me see if I found more time to this I will come back into it.

2016-11-08 18:17 UTC, trunet commented on braviarc/braviarc.py
> +                    stIdx = resp.get('result')[0][-1]['index']+1
http://pastebin.com/3EECCLWD

2016-11-11 17:26 UTC, trunet commented on braviarc/braviarc.py
> +        while True:
As we don't have any clue on how many channels, the only way is infinite loop and stop when I found an array of length 0.

If we know how to get the amount of channels on a previous API call, than we could only loop the necessary.

2016-11-11 17:27 UTC, trunet commented
No idea on how to fix the infinite loop, the rest is fixed. You can choose if you apply like this or not.

2016-11-11 17:38 UTC, merged

2016-11-11 17:38 UTC, aparraga commented
it's ok! I hate infinite loops, but anyway, it's ok as it!
thx!

2016-11-11 17:40 UTC, trunet commented
Thanks...

can you do a bump on the version?

On Fri, Nov 11, 2016 at 6:38 PM, Antonio Párraga Navarro <
notifications@github.com> wrote:

> it's ok! I hate infinite loops, but anyway, it's ok as it!
> thx!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/aparraga/braviarc/pull/9#issuecomment-260011908>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAMMeMn8x6tA88V_pgcIunvteA-0_3LXks5q9KgwgaJpZM4KssH0>
> .
>

2016-11-11 18:22 UTC, aparraga commented
Done!